### ISSUE TITLE
Add Todo Role

### ISSUE THREAD

**Issue by kynda** [kynda/playbooks#6]
- [ ] Install Todo.txt
- [ ] Install Plugins
- [ ] Install Recur
- [ ] Install Cronjobs
- [ ] Add tmuxinator template
- [ ] Only Bogun has role
